# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vinayak Das Gupta
email: Vinayak[dot]dasGupta[at]nuim[dot]ie
description: > # this means to ignore newlines until "baseurl:"
  This is my blogspace. I don't blog very often, but when I do, it is usually on my research. You can find more about me and my research at {{url}}http://vinayakdasgupta.com. Here, you can expect to read posts related to Digital Humanities; specifically, I am interested in early photography, data strcutures, data analysis and visualization. Views are my own etc. etc. etc. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bilusaurus
github_username:  vinayakdasgupta

# Build settings
markdown: kramdown
