# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vinayak Das Gupta
email: Vinayak[dot]dasGupta[at]nuim[dot]ie
description: > # this means to ignore newlines until "baseurl:"
  I blog about subjects related the technology and the humanities. Specifically, I tend to write about early photography, photo-collections, data-structures, data analysis and visualisation etc.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bilusaurus
github_username:  vinayakdasgupta
profile: http://vinayakdasgupta.com

# Build settings
markdown: kramdown
